### ISSUE TITLE
File uploads

### ISSUE THREAD

**Issue by JoeChapman** [UKHomeOffice/firearms#1]
Requirements discovered in investigation:
- Add a template mixin/partial for `input type="file"`
- Update or override controller#process (https://github.com/UKHomeOffice/passports-form-controller/blob/master/lib/form.js#L148) to lookup file from the request
  `req.body[key] || req.files[key] || ''`
- Update form view partial with `enctype='multipart/form-data'`
- Replace the Express BodyParser with a parser able to parse file data, such as `busboy-body-parser`

**Comment by easternbloc** [comment]
done
